# Generated by Django 3.0.6 on 2020-06-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='donation_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='donation_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='plasma_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='plasma_request',
            field=models.BooleanField(default=False),
        ),
    ]
