# Generated by Django 3.0.6 on 2020-06-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0004_profile_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diagnosis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospital_negative',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospital_positive',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='lab_negative',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='lab_positive',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Plasma',
        ),
    ]
