# Generated by Django 3.0.6 on 2020-06-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0005_auto_20200602_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='diagnosis_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hospital_negative',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hospital_positive',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lab_negative',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lab_positive',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_COVID_19_diagnosed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospital_which_labelled_negative',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospital_which_labelled_positive',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='lab_which_labelled_negative',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='lab_which_labelled_positive',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.IntegerField(choices=[(0, 'Khyber Pakhtunkhwah'), (1, 'Punjab'), (2, 'Sindh'), (3, 'Balochistan'), (4, 'Unspecified')], default=4),
        ),
    ]
