# Generated by Django 3.0.6 on 2020-06-04 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0006_auto_20200603_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
