# Generated by Django 3.0.7 on 2020-06-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0007_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.IntegerField(choices=[(0, 'Khyber Pakhtunkhwah'), (1, 'Punjab'), (2, 'Sindh'), (3, 'Balochistan'), (4, 'Unspecified'), (5, 'Islamabad Capital Territory'), (6, 'Azad Kashmir'), (7, 'Gilgit Baltistan'), (8, 'FATA')], default=4),
        ),
    ]
