# Generated by Django 3.0.7 on 2020-06-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0008_auto_20200604_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.IntegerField(choices=[(0, 'A+'), (1, 'A-'), (2, 'O+'), (3, 'O-'), (4, 'AB+'), (5, 'AB-'), (6, 'Unknown')]),
        ),
    ]
