# Generated by Django 3.0.7 on 2020-06-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0009_auto_20200606_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_COVID_19_diagnosed',
            new_name='date_covid_19_diagnosed',
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.IntegerField(choices=[(0, 'A+'), (1, 'A-'), (2, 'O+'), (3, 'O-'), (4, 'AB+'), (5, 'AB-'), (6, 'Unknown')], default=6),
        ),
    ]
