# Generated by Django 3.0.7 on 2020-06-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0010_auto_20200610_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='blood_group',
            new_name='blood',
        ),
    ]
