# Generated by Django 3.0.7 on 2020-06-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0011_auto_20200610_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='blood',
            new_name='blood_group',
        ),
    ]
