# Generated by Django 3.0.7 on 2020-06-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0012_auto_20200610_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.IntegerField(choices=[(0, 'A+'), (1, 'A-'), (2, 'B+'), (3, 'B-'), (4, 'O+'), (5, 'O-'), (6, 'AB+'), (7, 'AB-'), (8, 'Unknown')], default=6),
        ),
    ]
