# Generated by Django 3.0.7 on 2020-06-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0014_profile_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
