# Generated by Django 3.0.7 on 2020-06-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0015_auto_20200625_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blood_group',
            field=models.IntegerField(choices=[(0, 'A+'), (1, 'A-'), (2, 'B+'), (3, 'B-'), (4, 'O+'), (5, 'O-'), (6, 'AB+'), (7, 'AB-'), (8, 'Unknown')], default=8),
        ),
    ]
