# Generated by Django 3.0.7 on 2020-06-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0016_auto_20200625_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
