# Generated by Django 3.0.7 on 2020-07-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasma', '0018_auto_20200720_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
